# -*- coding: utf-8 -*-
"""Hello World with fpdf2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/PyFPDF/fpdf2/blob/master/tutorial/notebook.ipynb

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/PyFPDF/fpdf2/blob/master/tutorial/notebook.ipynb) <hr> [![Open In nbviewer](https://img.shields.io/badge/Open_In-nbviewer-blue?logo=jupyter)](https://nbviewer.org/github/PyFPDF/fpdf2/blob/master/tutorial/notebook.ipynb)

# Hello World with fpdf2
This [Jupyter notebook](https://jupyter.org/) demontrates some basic usage of the Python [fpdf2](https://github.com/PyFPDF/fpdf2) library
"""

# Installation avec PIP de fpdf2:
!pip install fpdf2

# Enable deprecation warnings:
import warnings
warnings.simplefilter('default', DeprecationWarning)

# Generate a PDF:
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.set_font('helvetica', size=48)
pdf.cell(txt="hello world")

interval_x, interval_y = 15, 30

circle_x, circle_y = 50, 50
pdf.set_line_width(2)
pdf.set_draw_color(240)
pdf.set_fill_color(r=0, g=0, b=0)
pdf.circle(x=circle_x, y=circle_y, r=50, style="FD")
pdf.text(x=circle_x+interval_x, y=circle_y+interval_y, txt='13')

circle_x, circle_y = 50, 120
pdf.circle(x=circle_x, y=circle_y, r=50, style="FD")
pdf.set_text_color(r=255, g=255, b=255)
pdf.text(x=circle_x+interval_x, y=circle_y+interval_y, txt='13')
pdf_bytes = pdf.output()

# Display the PDF in the notebook by embedding it as HTML content:
WIDTH, HEIGHT = 800, 400 
from base64 import b64encode
from IPython.display import display, HTML
base64_pdf = b64encode(pdf_bytes).decode("utf-8")
# display(HTML(f'<embed src="data:application/pdf;base64,{base64_pdf}" width="{WIDTH}" height="{HEIGHT}" type="application/pdf">'))

# Diplay a download button:
display(HTML(f'<a download="fpdf2-demo.pdf" href="data:application/pdf;base64,{base64_pdf}">Click to download PDF</a>'))